# Generated by Django 3.2.8 on 2021-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_coffee',
            name='image',
            field=models.ImageField(blank=True, height_field=800, null=True, upload_to='products', width_field=600),
        ),
    ]
