# Generated by Django 3.2.8 on 2021-10-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
