# Generated by Django 3.2.8 on 2021-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_product_coffee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_coffee',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
