# Generated by Django 3.2.8 on 2021-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_product_coffee_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
