# Generated by Django 3.2.8 on 2021-10-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_order_delivery_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prev_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
