# Generated by Django 3.2.8 on 2021-10-17 18:54

from django.db import migrations, models
import market.models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_order_prev_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2)),
                ('p_hash', models.CharField(default=market.models.createHash, max_length=64, unique=True)),
                ('hash', models.CharField(default=None, max_length=64, null=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
