# Generated by Django 3.2.8 on 2021-10-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_blockchain_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='p_hash',
            new_name='prev_hash',
        ),
    ]
