# Generated by Django 3.2.8 on 2021-10-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prev_hash',
        ),
    ]
