# Generated by Django 3.2.8 on 2021-10-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_order_prev_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.order'),
        ),
    ]
