# Generated by Django 3.2.8 on 2021-10-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_blockchain_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
