# Generated by Django 3.2 on 2021-10-17 22:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_auto_20211017_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockchain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
